stages:
  - sast
  - php_build
  - js_build
  - deploy

sast:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
      --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
      --volume "$PWD:/code"
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    paths: [gl-sast-report.json]

php_build:
  stage: php_build
  image: composer
  script:
    - composer install -on --ignore-platform-reqs --no-progress
    - composer dump-autoload --optimize
  artifacts:
    paths:
      - vendor/
    when: on_success
    expire_in: 1h
  only:
    - develop
    - master

apidoc_build:
  stage: js_build
  image: node:8.11.2
  script:
    - npm install apidoc -g
    - apidoc -i docs/ -o public/apidoc/
  artifacts:
    paths:
      - public/apidoc/
    when: on_success
    expire_in: 1h
  only:
    - develop

js_build:
  stage: js_build
  image: node:11.2
  script:
    - npm install
    - npm run prod
  artifacts:
    paths:
      - public/build/
      - public/fonts/
    when: on_success
    expire_in: 1h
  only:
    - develop

deploy:develop:
  stage: deploy
  script:
    - apt-get update && apt-get install -y
      ssh
      rsync

    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY_DEV" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    - echo "$ENV_DEV" > ./.env

    - mkdir ./ssl
    - echo "$SSL_CERTIFICATE" > ./ssl/certificate.crt
    - echo "$SSL_PRIVATE_KEY" > ./ssl/private.key


    - cp docker-compose.development.yml docker-compose.yml
    - rm docker-compose.yml.*

    - rm -f ./public/storage
    - ln -s ../storage/app/public/ ./public/storage

    - rm -rf ./.git
    - rm -rf ./node_modules
    - rm -rf ./tests
    - rm -rf ./docs

    - ssh -o StrictHostKeyChecking=no $SSH_USER_DEV@$SERVER_HOST_DEV "mkdir -p /var/www/tagit"

    - rsync -az --exclude-from=.gitlab-ci-exclude --no-perms --no-owner --no-group --delete-during -e "ssh -o StrictHostKeyChecking=no" . $SSH_USER_DEV@$SERVER_HOST_DEV:/var/www/tagit
    - ssh -o StrictHostKeyChecking=no $SSH_USER_DEV@$SERVER_HOST_DEV "cd /var/www/tagit && docker-compose up -d --force-recreate --remove-orphans && sleep 60 && docker exec tagit_php /bin/bash /var/www/init_dev.sh"
  only:
    - develop
