version: '3'

services:
  primary:
    hostname: 'primary'
    image: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=primary
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=JjSMbuFhVrcU
      - PG_DATABASE=database
      - PG_USER=tagit_user
      - PG_PASSWORD=ZEvLrAXJLPCv
      - PG_ROOT_PASSWORD=root
      - PG_PRIMARY_PORT=5432
    volumes:
      - pg-primary-vol:/pgdata
    ports:
      - "5434:5432"
    networks:
      - crunchynet
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
          - node.role == worker
  replica:
    image: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=replica
      - PG_PRIMARY_HOST=primary
      - PG_PRIMARY_PORT=5432
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=JjSMbuFhVrcU
      - PG_DATABASE=database
      - PG_USER=tagit_user
      - PG_PASSWORD=ZEvLrAXJLPCv
      - PG_ROOT_PASSWORD=root
    volumes:
      - pg-replica-vol:/pgdata
    ports:
      - "5435:5432"
    networks:
      - crunchynet
    deploy:
      placement:
        constraints:
          - node.labels.type != primary
          - node.role == worker

  nginx:
    image: nginx:latest
    container_name: tagit_nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENV: production
      SERVER_NAME: tagitgamesmaker.com
      SSL: "on"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx_ssl.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/var/www/ssl
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - crunchynet
  php:
    build: 'docker/php/'
    container_name:  tagit_php
    volumes:
      - ./:/var/www
      - ./docker/php/crontasks:/var/crontasks
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    command: /bin/bash -c "cp /var/crontasks /var/spool/cron/crontabs/root && chown root:root /var/spool/cron/crontabs/root && chmod 0600 /var/spool/cron/crontabs/root && /usr/bin/supervisord -n -c /var/www/docker/php/supervisord.conf"
    depends_on:
      - primary
      - replica
    links:
      - primary:database_host_master
      - replica:database_host_slave
    restart: unless-stopped
    networks:
      - crunchynet

networks:
  crunchynet:

volumes:
  pg-primary-vol:
  pg-replica-vol:
