version: '3'

services:
  db:
    image: "postgres:11.1"
    ports:
      - "5432:5432"
    restart: unless-stopped
    container_name: scrapbook_db
    volumes:
      - db_data:/data/postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PGDATA: /data/postgres
  nginx:
    image: nginx:latest
    container_name: scrapbook_nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENV: production
      SERVER_NAME: domen
      SSL: "on"
    volumes:
      - ./:/var/www
      - ./ssl:/var/www/ssl
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - php
  php:
    build: ./
    container_name: scrapbook_php
    volumes:
      - ./:/var/www
      - ./docker/crontasks:/var/crontasks
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    command: /bin/bash -c "cp /var/crontasks /var/spool/cron/crontabs/root && chown root:root /var/spool/cron/crontabs/root && chmod 0600 /var/spool/cron/crontabs/root && /usr/bin/supervisord -n -c /var/www/docker/supervisord.conf"
    depends_on:
      - db
    links:
      - db:database_host
    restart: unless-stopped
volumes:
  db_data:
